### ISSUE TITLE
Arguments manquants à la commande asciidoctor-pdf

### ISSUE THREAD

**Issue by roddet** [alvinberthelot/slides-js#1]
Salut Alvin,

J'ai voulu tester la mécanique de génération de pdf, j'ai suivi les indications du readme et la commande suivante ne fonctionne pas 

```
➜  slides-js git:(master) ✗ ruby ../asciidoctor-pdf/bin/asciidoctor-pdf
Usage: asciidoctor [OPTION]... FILE...
Translate the AsciiDoc source FILE or FILE(s) into the backend output format (e.g., HTML 5, DocBook 4.5, etc.)
(...)
````
La commande semble incomplète. Il doit manquer au moins les fichiers à transformer par exemple 

```
ruby ../asciidoctor-pdf/bin/asciidoctor-pdf *.adoc
```

Avec cela j'ai un format "book" et pas "slides", manque t-il des informations sur le thème utilisé ?

**Comment by alvinberthelot** [comment]
Salut,

J'avoue j'ai été un peu léger sur la documentation de génération d'autant qu'elle date un peu ...

Voilà ce que je fais actuellement.

Step 1 - Je clone le dépôt des slides
Step 2 - Je clone le dépôt de mon thème (format, taille des polices, etc.) que tu pourras retrouver ici : [asciidoctor-theme-webyousoon](https://github.com/webyousoon/asciidoctor-theme-webyousoon)
Step 3 - Pour une slide en particulier (js-functions par exemple) je lance la commande suivante : 

```
asciidoctor-pdf -a pdf-style=asciidoctor-theme-webyousoon/webyousoon-theme.yml slides-js/js-functions.adoc
```

Normalement avec ça tu devrais mieux t'en sortir.

Je n'ai pas encore mis à jour cette documentation car au final la partie la plus chiante c'est de se taper l'install Asciidoctor, Ruby et compagnie ; que je ne fais plus du tout en passant par une [image Docker](https://hub.docker.com/r/asciidoctor/docker-asciidoctor/). D'ailleurs à ce sujet tu feras attention je vais chercher l'exécutable différemment.

Bref j'aimerai revoir en profondeur ma documentation sur cette partie génération mais ça va me prendre un peu de temps et pour le moment je me concentre sur le contenu.

N'hésite pas à me dire si tu es bloqué car j'aimerai bien convertir d'autre producteurs de contenus à adopter cette approche ;)

**Comment by roddet** [comment]
Parfait, le thème fonctionne !
